### ISSUE TITLE
Couldn't recognize cards with card number length other than 16 or 19

### ISSUE THREAD

**Issue by intrueder** [Nick-Knock/Vendor#2]
For numbers `4222222222222` (VISA) and `343434343434343` (American Express) program results with `"You entered the wrong number"` message

**Comment by intrueder** [comment]
This problem prevents to check other solutions.

**Comment by Nick-Knock** [comment]
Reference to a new repository with source file, which contains one project for all the tasks, changed according to your remarks.
https://github.com/Nick-Knock/All_Tasks.git
